### ISSUE TITLE
Linking xmenu to pywal?

### ISSUE THREAD

**Issue by vaskark** [phillbush/xmenu#11]
Hello. Is the any way to link xmenu to the pywal colour-changing scheme? It already does the background colour fine (color0), and I think normal text is using color7, but selected text/bg is still just white/blue.

Is this possible right now?
Thanks.

**Comment by phillbush** [comment]
The background and foreground of xmenu follows the colors set by pywal because pywal sets the following X resources:

```
*background
*foreground
```

And xmenu uses the following X resources, which matches those set by pywal (because of the `*` character at the beginning of them):

```
xmenu.background
xmenu.foreground
```

These are the only xmenu colors that match pywal colors.  
pywal also sets the resources `*color0` to `*color15`, but xmenu does not use resources that matches them. Instead, xmenu uses `xmenu.selforeground` for the foreground of the selected item, `xmenu.border` for the color of the border, etc.

You should edit your `~/.Xresources` file and copy the color generated by pywal for `*color4` and paste it as the value for `xmenu.selforeground`, for example. Or [create a templeate](https://github.com/dylanaraps/pywal/tree/master/pywal/templates) for pywall to expand the resources it creates.

**Comment by phillbush** [comment]
The template file for X resources is [`colors.Xresources`](https://github.com/dylanaraps/pywal/blob/master/pywal/templates/colors.Xresources),  Just edit it to put the following lines at the end:

```
xmenu.selbackground: {color4}
xmenu.selforeground: {foreground}
```

And move the file to your `~/.config/wal/templates` and it should work (or I think so, I do not have pywal in my machine right now so I can not test).

**Comment by vaskark** [comment]
Thanks! Works like a charm.
