### ISSUE TITLE
Support of icon-theme

### ISSUE THREAD

**Issue by raspbeguy** [phillbush/xmenu#27]
Hello,

I think that being able to choose icons in the current icon-theme would be a very nice feature (you can see a list of those icons with `gtk3-icon-browser` for example).

This feature is present in [Rofi](https://github.com/davatorium/rofi).

**Comment by phillbush** [comment]
Hello,

In order to make the development and feature set of xmenu simpler and to make it extendable for most use cases, xmenu is unaware of the location of the icons.  In fact, the task of specifying menu entries and their icons should be let to the wrapper script that calls xmenu. That's also why xmenu don't list .desktop entries by itself as Rofi does, but depends on an [script](https://github.com/OliverLew/xdg-xmenu) for that.  Thus, users can use whatever icon image they like, be it from a icon theme directory or not.

Another problem is that some themes use .svg image files, which Imlib2 (the library that handle image files for xmenu) does not support.

It may be simple to write a script that reads the `index.theme` file in a icon theme directory and uses `find(1)` to find the image file corresponding to an icon there. I will probably write such a script later.

**Comment by raspbeguy** [comment]
I understand and it makes sense. Thanks for clarifying.
