### ISSUE TITLE
[Issue] no max number of lines

### ISSUE THREAD

**Issue by The-Repo-Club** [phillbush/xmenu#32]
there seems to be an issue with there not being a max number of lines before it would scroll so if you had 200 items all on there own line the menu would be too long and go off the page is there any way to set the max number then after that it will scroll :) kind of like -l does for dmenu

**Comment by phillbush** [comment]
That's a great idea: make a menu higher than the screen to scroll.
I just added that to my todo list and gonna be implementing it soon.

**Comment by The-Repo-Club** [comment]
would be good if you can set the max height too not just if its bigger then the screen :)

**Comment by phillbush** [comment]
I added the `xmenu.maxItems` X resource and the `config.max_items` config.h option.  
Both can be used to select the maximum number of items in a menu.  
The scrolling mechanism is kinda hacky, you need to click the arrows in order to scroll the items.

If you have any tip on how to improve it, please comment in this thread.
