### ISSUE TITLE
Performance issue with many icons

### ISSUE THREAD

**Issue by OliverLew** [phillbush/xmenu#7]
I don't know the exact issue in code, here is how I'd show that in an example:
```
xmenu << EOF
IMG:icon.png	aaa
(repeat ~ 30 times)
EOF
```
The icon is just a 24x24 png file.

If I move the cursor up and down rapidly in a list when there is a lot of icons, the highlighting won't be able to follow closely to (lag behind) the cursor and one cpu thread (the process is the X server) will be at 80% on my laptop if I keep moving the cursor. The gif below demonstrates the situation that my cursor is easily ahead of the highlighting by half round.

And here is my observation of another menu app `jgmenu`. `jgmenu` will only highlight part of the items that the cursor moves through and the highlighting does not lag behind no matter how fast the cursor moves. Hope this helps :)

![Peek 2020-07-28 23-58](https://user-images.githubusercontent.com/12032219/88690632-70d61300-d12e-11ea-9bd9-cab33761d790.gif)

**Comment by phillbush** [comment]
The problem is probably that Xmenu tries to redraw the icon every time the cursor moves in and out of an item.  
I'm going to change this to make xmenu draw each icon once and then only copy it when the cursor moves between them.  
I think that copying a drawn image is faster than redrawing it.

**Comment by phillbush** [comment]
Done.  
The problem was indeed with drawing the icons every time the item changed from selected to unselected state. Now the icons are drawn once, at the beginning of the program, and copied when needed.

In the next release I will do this approach (drawing once, copying when needed) with other widgets too: the icon text, the triangle of submenus, etc. Although drawing them does not requires such CPU time as drawing images.

**Comment by OliverLew** [comment]
Thanks, that's really fast fix! I just built the latest code locally and tested it with my use cases, and there is no lagging anymore. The cpu usage is now around 20%. I'll close this issue then since it's fixed.

**Comment by OliverLew** [comment]
There seems to be a small issue brought by the above commit https://github.com/phillbush/xmenu/commit/675a2008a6c9ad34d199aebdac6447d33a9cb53e (I tested both this commit and the one before): the start up time is rather noticeable now.

I tested with my use case where there are 110+ icons (they are all the desktop entries I have) in multiple submenus. The start up time of v3.4 is within two frames in my 30fps screenrecording, or 0.03~0.06 seconds. While that of v3.4.1 is within 8 frames, which is about a quarter of one second. This is noticeable in some cases, e.g. if you bind xmenu to mouse click. If you increase the number of icons, the delay gets longer.

Well I only provide my real use case so you and other users can decide whether this delay is acceptable in normal usages and whether it is a issue need fiixing :)

**Comment by phillbush** [comment]
Hmm, since now all drawing is done at the program initialization rather than during the actual usage, the time delay was brought to the program initialization.

Have you tried to run `xmenu` with the same input but with the option `-i` (which disable icons) and saw if the delay persists? If it does not persists, then the problem is indeed with the icon initialization.

A solution I could find is to draw the menus on demand, that is, instead of drawing all menus and submenus at once at program initialization, draw a menu when it is invoked.

I will try this approach in a next release.

**Comment by OliverLew** [comment]
> Have you tried to run `xmenu` with the same input but with the option `-i` (which disable icons) and saw if the delay persists? If it does not persists, then the problem is indeed with the icon initialization.

Now I have tried that and yes the start up is as fast as before.

> A solution I could find is to draw the menus on demand, that is, instead of drawing all menus and submenus at once at program initialization, draw a menu when it is invoked.

That's exactly what I thought, I think loading only a fraction of the many icons a time will reduce the delay to an acceptable level.

**Comment by phillbush** [comment]
Just did a new commit that draw menus on demand.  
Can you test if the delay persists for your use case?

**Comment by OliverLew** [comment]
Wow, that's really quick, thanks! I pull the lasted commit and `xmenu` now does not has the long delay anymore, works wonderful!
